---
title: "Catalan political parties palette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Catalan political parties palette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(modthemes)
library(tidyverse)
```


## Examples

This palette provides a named vector with the official colours of major Catalan political parties active between 2010 and 2022.


```{r vector}
catparties_palette
```


This palette can be used for plotting in {ggplot2} or (unnaming it), {tmap}


```{r plot example}

elections_2017 <- data.frame(
  stringsAsFactors = FALSE,
       check.names = FALSE,
                Party = c("C's","JxCat","ERC",
                          "PSC","Catalunya en Comú Podem","CUP","PP"),
          `Vote.%` = c(25.35, 21.66, 21.38, 13.86, 7.46, 4.46, 4.24),
             Seats = c(36L, 34L, 32L, 17L, 8L, 4L, 4L)
   )

ggplot(elections_2017, aes(x = reorder(Party, desc(`Vote.%`)), y = `Vote.%`, fill = Party)) + 
  geom_bar(stat = "identity") + 
  scale_fill_manual("Party", values = modthemes::catparties_palette) +
  labs(title = "Vote % of main political parties in 2017 Catalan elections",
       caption = "Data: IDESCAT",
       x = "Party") + 
  theme_minimal(base_family = "Roboto condensed") + 
  theme(legend.position = "none")
```
